Week 2 fred mcburnett
learn-academy-2022-hotel/week-2-assessment-Fred-H-McBurnett pull request #1
Opened 2022-12-12 16:30 UTC by Fred-H-McBurnett

# Submitting Week 2 Assessment

### ✅ Completed Files

Select the following as confirmation that the files in this repository are complete.

- [ ] Coding Challenges
- [ x ] Coding Concepts
- [ x ] Interview Questions

### 📝 Feedback

If you would like specific feedback on a particular problem please leave details here:
I struggled with creating the actual JEST test to get the pass of a "Good Failure", so I was unable to complete the last two functions in code-challenges.test.js.  James was very helpful in helping me to figure out how to write the JEST part of the test, where we describe what we expect to see.  I was not in class on the day this was covered, because of the family emergency.  That is not an excuse, just a statement and why I had asked for some assistance yesterday.

2022-12-14 16:29 UTC, nmaresrivera11 commented on code-challenges.test.js
>  // --------------------3) Create a function that takes in a string and logs the index of the first vowel.
Hey Fred, you did an awesome job on the rest of your assessment. I want to provide you with some pseudocode and have you try this question again using the pseudocode I provide to you.
Pseudo-code:
1. I want to create a function that will be called (firstVowel)
2. My function will take an argument of a string (from the given variables vowelTester1, vowelTester2, vowelTester3
3. May want to declare what letters are vowels
4. I want my function to iterate through the string to look for any vowels(for loop or use a higher order function, or string methods that iterate over strings)
5. I want to return the index of that string

2022-12-14 16:31 UTC, nmaresrivera11 commented on code-challenges.test.js
> +//     for (i = 0; i < array.length; i++) {
This one is so close, you just need to upperCase the first index and then either slice or add a substring method to return the rest of the string as lowercase with the first letter capitalized. Give it a try!

2022-12-14 16:32 UTC, nmaresrivera11 requested changes
Hi Fred, I have provided some pseudo code for question #3 in Code Challenges. From this pseudo code try to create your function to find the vowels in the given variable strings. There is also a note on question #2. Your assessment looks really good! You did amazing on the interview questions and your explanations in the concepts also look very good.

2022-12-16 21:53 UTC, SunkissedQueen approved these changes

2022-12-16 22:10 UTC, closed without merging